### ISSUE TITLE
Workspaces

### ISSUE THREAD

**Issue by ertseyhan** [TaylanTatli/dotfiles#1]
Merhaba,

Panel'de sol tarafta olması gereken workspace simgelerinde sorun yaşıyorum.
![](http://i.hizliresim.com/28J7nA.png)

Simgeler panel'e eklenmiyor. Uzun süre inceledim ancak sorunun kaynağını bulamadım. Panel gereksinimlerinden birisinin eksik olduğunu düşünüyorum zira panel başlatılırken 'Unknown command' uyarısı veriyor. Script'in debug çıktısı şu şekilde;

![](http://i.hizliresim.com/4baLzG.png)

Bu hata veya başka bir sebepten dolayı workspace simgeleri panelde gözükmüyor.
Bir fikriniz var mı?

bspwm: v0.9-126-gb1d9653
lemonbar: v38f69d8

**Comment by TaylanTatli** [comment]
Merhaba.
panel_bar dosyası $PATH klasörlerinden birinde değil mi? panel kendisiyle beraber diğer betikleri de çalıştırıyor ve workspace iconlarının olduğu kısım panel_bar betiğinde.

Ben hepsini ~/.config/bspwm/bar klasöründe toplamıştım ve oradan çalıştırılıyordu.

.profile dosyasına şöyle iki satır eklemiştim panel için:
```
export PATH=$HOME/bin:$HOME/.config/bspwm/bar:$PATH
export PANEL_FIFO=/tmp/panel-fifo
```
Sen de dosyaları hangi klasörde tutuyorsan onu ekleyerek panel'in diğer betikleri otomatik çalıştırmasını sağlayabilirsin. Onun dışında sadece sutils paketindeki betikler eksik olabilir ama workspace'i etkilemeyeceğinden muhtemelen sorun panel'in panel_bar'ı çalıştıramıyor olmasıdır.

Umarım yardımcı olabilmişimdir.

**Comment by ertseyhan** [comment]
Öncelikle ilginiz için teşekkür ederim.

Kod betiklerinin yer aldığı klasörler PATH dizininde ekli. O yönden sıkıntı yok. Panel'deki workspace simgeleri hariç diğer herşey sorunsuz çalışıyor şuan.

panel_bar içerisindeki bir satır 'Unknown command' hatası verdiriyor. Muhtemelen hata bundan kaynaklı. Betiği inceliyorum ancak `goto` değişkeninden başka gözüme çarpan olası bir eksiklik yok malesef.

Çift monitör kullandığım için, `bspc desktop -f` komutu sorun yaratıyor olabilir mi?

**Comment by TaylanTatli** [comment]
Sorunu buldum. Tabi önce şunu öğrenmem lazım. bspwm'yi AUR'dan mı kurdunuz? Eğer öyleyse bazı kodlar değişti.  Bspwm artık kullanmadığım için güncellemedim hiçbir şeyi.
```
bspc control --subscribe > "$PANEL_FIFO" &
```
kısmını aşağıdaki ile değiştirin.

```
bspc subscribe report > "$PANEL_FIFO" &
```

Daha düzgün bir lemonbar paneli yazdım ama bspwm için değil. O yüzden bspwm kısmındaki biraz eski kaldı ve hataları var.

**Comment by ertseyhan** [comment]
Evet, sorun düzeldi.

Sürüm'den kaynaklanacak farklılıkları tahmin ederek sürüm numarasını belirttiğim iyi olmuş. Fazla zaman ayıramadığım için bu farklılıkları inceleme şansım yoktu.

Güzel çalışmalarınız var bu konuda. Eminim community çalışmalarınızı görmek isteyecektir.

Sorun çözüldüğüne göre konu'yu kapatıyorum, iyi çalışmalar dilerim.

**Comment by TaylanTatli** [comment]
Teşekkür ederim. Sorunun çözülmesine sevindim. Size de.
